correcting cicd11

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -48,7 +48,7 @@ jobs:
 
 
     - name: run tests
-      run: uv run pytest test || echo "Tests failed" >> test_status.txt
+      run: uv run pytest tests || echo "Tests failed" >> test_status.txt
       continue-on-error: true
 
     - name: Check if tests passed
